### ISSUE TITLE
com.auth0.jwt.exceptions.SignatureVerificationException in HMACAlgorithm.java:57

### ISSUE THREAD

**Issue by GeoZac** [GeoZac/unconv_spring#493]
## Error in Unconv Spring

**com.auth0.jwt.exceptions.SignatureVerificationException** in **HMACAlgorithm.java:57**
The Token's Signature resulted invalid when verified using the Algorithm: HmacSHA256

[View on Bugsnag](https://app.bugsnag.com/unconventional/unconv-spring/errors/66ff7514dab091357e1b4877?event_id=66ff75650100d39c4fac0000&i=gh&m=ci)

## Stacktrace

    HMACAlgorithm.java:57 - com.auth0.jwt.algorithms.HMACAlgorithm.verify

[View full stacktrace](https://app.bugsnag.com/unconventional/unconv-spring/errors/66ff7514dab091357e1b4877?event_id=66ff75650100d39c4fac0000&i=gh&m=ci)

*Created by George Zacharia via Bugsnag*

**Comment by GeoZac** [comment]
Stacktrace
`com.auth0.jwt.exceptions.SignatureVerificationException: The Token's Signature resulted invalid when verified using the Algorithm: HmacSHA256
        at com.auth0.jwt.algorithms.HMACAlgorithm.verify(HMACAlgorithm.java:57)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:463)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:445)
        at com.unconv.spring.security.filter.JWTUtil.validateTokenAndRetrieveUsername(JWTUtil.java:69)
        at com.unconv.spring.security.filter.JWTAuthenticationFilter.doFilterInternal(JWTAuthenticationFilter.java:80)`
